# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ['.env']

silent: true

includes:
  cleanup: https://raw.githubusercontent.com/sig9org/tasks/main/examples/remote/cleanup.yml
  os: https://raw.githubusercontent.com/sig9org/tasks/main/examples/remote/os.yml
  time: https://raw.githubusercontent.com/sig9org/tasks/main/examples/remote/time.yml

tasks:
  default:
    cmds:
      - task --list
