# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ['.env']

silent: true

includes:
  _task: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_all.yml

vars:
  GENERATE_CLEANUP_DIRS:
    - examples
    - tasks

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_cleanup:start

  generate:cleanup:
    internal: true
    cmds:
      - for: { var: GENERATE_CLEANUP_DIRS }
        cmd: mkdir -p "{{.ITEM}}" && rm -rfv "{{.ITEM}}"/* | sed 's/^/[DELETE]/'

  generate:
    aliases: [g]
    desc: "Generate task files"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: generate:cleanup
      - gotasky

  generate-debug:
    aliases: [gd]
    desc: "Generate task files (Debug)"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: generate:cleanup
      - gotasky -debug
