tasks:
  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start
