tasks:
  docker-check:
    aliases: [dc]
    desc: "Display unhealthy containers"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_docker:check

  docker-ps:
    aliases: [dp]
    desc: "Display all containers"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_docker:ps

  docker-restart:
    aliases: [dr]
    desc: "Restart unhealthy containers"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_docker:restart
