tasks:
  os-check-update:
    aliases: [oc]
    desc: "Check for available OS package updates"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:check

  os-remove:
    aliases: [or]
    desc: "Remove unnecessary OS packages and dependencies"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:remove

  os-update:
    aliases: [ou]
    desc: "Update and upgrade OS packages"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:update
