# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  tags:
    internal: true
    cmds:
      - skopeo list-tags docker://docker.io/{{.DOCKER_ACCOUNT}}/{{.DOCKER_REPO}} | jq -r '.Tags[]' | sort -V
