# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ['.env']

silent: true

includes:
  _task: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_all.yml

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_cleanup:start

  tf-apply:
    aliases: [ta]
    desc: "terraform apply -auto-approve"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _tf-cml:apply

  tf-destroy:
    aliases: [td]
    desc: "terraform destroy -auto-approve"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _tf-cml:destroy

  tf-init:
    aliases: [ti]
    desc: "terraform init"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start
      - task: _tf-cml:init

  tf-plan:
    aliases: [tp]
    desc: "terraform plan"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _tf-cml:plan

  tf-tag:
    aliases: [tt]
    desc: "terraform apply -auto-approve"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _tf-cml:tag
