tasks:
  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start

  _cleanup:start:
    internal: true
    cmds:
      - task: _cleanup:shell
      - task: _cleanup:refresh

  _cleanup:shell:
    internal: true
    dir: "{{.USER_WORKING_DIR}}"
    platforms: [darwin, linux]
    cmds:
      - for: { var: CLEANUP_DIRS }
        cmd: find . -type d -name "{{.ITEM}}" -print -prune -exec rm -rf {} + | sed 's/^/[DELETE]/'
      - for: { var: CLEANUP_FILES }
        cmd: find . -name "{{.ITEM}}" -print -delete | sed 's/^/[DELETE]/'

  _cleanup:refresh:
    internal: true
    dir: "{{.ROOT_DIR}}"
    env:
      TASK_X_REMOTE_TASKFILES: 1
    cmds:
      - task --yes --download --force --list-all > /dev/null 2>&1
