# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: ['project.ini']

silent: true

includes:
  _task: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_all.yml

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _task:_cleanup:start

  go-build:
    aliases: [gb]
    desc: "Build a binary for the current platform"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:build

  go-build-all:
    aliases: [gba]
    desc: "Cross-compile release binaries for all platforms"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:build-all

  go-clean:
    aliases: [gc]
    desc: "Delete the contents of the distribution directory"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:clean

  go-register:
    desc: "Register the latest tagged version on pkg.go.dev"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:register

  go-run:
    aliases: [gr]
    desc: "Run the application"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:run

  go-test:
    aliases: [gt]
    desc: "Run the Go test suite"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:test

  go-version:
    aliases: [gv]
    desc: "Show version information"
    cmds:
      - defer:
          task: _task:_time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _go:version
