# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ['.env']

silent: true

includes:
  _cleanup: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_cleanup.yml
  _os: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_os.yml
  _time: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_time.yml

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start

  os-check:
    aliases: [oc]
    desc: "Check for available OS package updates"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:check

  os-remove:
    aliases: [or]
    desc: "Remove unnecessary OS packages and dependencies"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:remove

  os-update:
    aliases: [ou]
    desc: "Update and upgrade OS packages"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _os:update
