tasks:
  start:
    internal: true
    cmds:
      - task: start:shell

  start:shell:
    internal: true
    dir: "{{.USER_WORKING_DIR}}"
    platforms: [darwin, linux]
    cmds:
      - for: { var: CLEANUP_DIRS }
        cmd: find . -type d -name "{{.ITEM}}" -print -prune -exec rm -rf {} +
      - for: { var: CLEANUP_FILES }
        cmd: find . -name "{{.ITEM}}" -print -delete
