tasks:
  docker-check:
    aliases: [dc]
    desc: 'Display unhealthy containers'
    cmds:
      - defer:
          task: time
          vars:
            START_TIME: '{{.START_TIME}}'
      - docker ps -a --filter "health=unhealthy"

  docker-ps:
    aliases: [dp]
    desc: 'Display all containers'
    cmds:
      - defer:
          task: time
          vars:
            START_TIME: '{{.START_TIME}}'
      - 'docker ps --format "table {{"{{"}}.ID{{"}}"}}\t{{"{{"}}.Image{{"}}"}}\t{{"{{"}}.Status{{"}}"}}\t{{"{{"}}.Ports{{"}}"}}\t{{"{{"}}.Names{{"}}"}}"'

  docker-restart:
    aliases: [dr]
    desc: 'Restart unhealthy containers'
    cmds:
      - defer:
          task: time
          vars:
            START_TIME: '{{.START_TIME}}'
      - docker restart $(docker ps -a --filter "health=unhealthy" -q)
