tasks:
  os-check:
    aliases: [oc]
    deps: [_time:start]
    desc: "Check for available OS package updates"
    cmds:
      - defer: { task: _time:end }
      - task: _os:check

  os-remove:
    aliases: [or]
    deps: [_time:start]
    desc: "Remove unnecessary OS packages and dependencies"
    cmds:
      - defer: { task: _time:end }
      - task: _os:remove

  os-update:
    aliases: [ou]
    deps: [_time:start]
    desc: "Update and upgrade OS packages"
    cmds:
      - defer: { task: _time:end }
      - task: _os:update
