tasks:
  cleanup:
    aliases: [c]
    deps: [_time:start]
    desc: "Remove temporary and unnecessary files"
    cmds:
      - defer: { task: _time:end }
      - task: _cleanup:start

  build:
    aliases: [b]
    deps: [_time:start]
    desc: "Generate task files"
    cmds:
      - defer: { task: _time:end }
      - rm -rf examples/* tasks/*
      - gotasky
