tasks:
  generate:
    aliases: [g]
    desc: "Generate task files"
    cmds:
      - defer:
          task: time
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: generate:cleanup
      - gotasky

  generate-debug:
    aliases: [gd]
    desc: "Generate task files (Debug)"
    cmds:
      - defer:
          task: time
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: generate:cleanup
      - gotasky -debug

  generate:cleanup:
    internal: true
    cmds:
      - for: { var: GENERATE_CLEANUP_DIRS }
        cmd: mkdir -p "{{.ITEM}}" && rm -rfv "{{.ITEM}}"/* | sed 's/^/[DELETE]/'
