tasks:
  uv-freeze:
    aliases: [uf]
    deps: [_time:start]
    desc: "Export installed packages"
    cmds:
      - task: _uv:freeze
      - defer: { task: _time:end }

  uv-sync:
    aliases: [us]
    deps: [_time:start]
    desc: "Sync dependencies and upgrade all packages"
    cmds:
      - task: _uv:sync
      - defer: { task: _time:end }
