# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ['.env']

silent: true

includes:
  _cleanup: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_cleanup.yml
  _time: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_time.yml
  _uv: https://raw.githubusercontent.com/sig9org/tasks/main/tasks/_uv.yml

tasks:
  default:
    cmds:
      - task --list

  cleanup:
    aliases: [c]
    desc: "Cleanup unnecessary files"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _cleanup:start

  uv-freeze:
    aliases: [uf]
    desc: "Export installed packages"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _uv:freeze

  uv-sync:
    aliases: [us]
    desc: "Sync dependencies and upgrade all packages"
    cmds:
      - defer:
          task: _time:end
          vars:
            START_TIME: '{{.START_TIME}}'
      - task: _uv:sync
